/*
 * @description: 2D编辑器全局数据
 * @author: MC.Yang
 */
import {KeydownType, Meta2d} from "@meta2d/core";
import {Editor2DConfig, Editor2DData, Editor2DOptions, Editor2DPen, Editor2DPoint} from "./editor2d-global-type";

declare global {
    // 核心 - 使用 var 防止重复声明错误
    var meta2d: Meta2d;
    // Canvas2SVG 类型定义
    var C2S: (new(width: number, height: number) => any) | undefined;
}

/**
 * 2D编辑器全局图纸点数据
 */
export const globalEditor2DPoint: Editor2DPoint = {
    x: 0,
    y: 0,
}

/**
 * 2D编辑器全局图纸属性
 */
export const globalEditor2DData: Editor2DData = {
    pens: [],
    x: 0,
    y: 0,
    scale: 0,
    origin: globalEditor2DPoint,
    center: globalEditor2DPoint,
    name: '',
    folder: '',
    fileType: '',
    mapProps: {
        color: '#222222',
        penBackground: '',
        background: '',
        backGroundImage: '',
        rule: true,
        ruleColor: '#888888',
        grid: true,
        gridColor: '#e2e2e2',
        gridSize: 10,
        gridRotate: 90
    },
    socketConfig: {
        url: ''
    },
    mqttConfig: {
        mqtt: '',
        mqttTopics: '',
        mqttOptions: {
            clientId: '',
            username: '',
            password: '',
            customClientId: false,
        },
    },
    httpConfig: [
        {
            http: '',
            method: '',
            httpTimeInterval: 1000,
            httpHeaders: {},
        },
    ],
}

/**
 * 2D编辑器全局图纸选项
 */
export const globalEditor2DProps: Editor2DOptions = {
    fontFamily: '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
    fontSize: 12,
    lineHeight: 1.5,
    textAlign: 'center',
    textBaseline: 'middle',
    color: '#222222',
    activeColor: '#278df8',
    hoverColor: 'rgba(39,141,248,0.50)',
    anchorColor: '#278DF8',
    hoverAnchorColor: '#FF4101',
    anchorRadius: 4,
    anchorBackground: '#fff',
    dockColor: 'rgba(39,141,248,0.50)',
    dockPenColor: '#1890FF',
    dragColor: '#1890ff',
    rotateCursor: 'rotate.cur',
    rightCursor: 'right.cur',
    downCursor: 'down.cur',
    hoverCursor: 'pointer',
    minScale: 0.1,
    maxScale: 10,
    keydown: KeydownType.Document,
    grid: true,
    gridSize: 10,
    gridColor: '#e2e2e2',
    rule: true,
    ruleColor: '#888888',
    drawingLineName: 'curve',
    interval: 30,
    animateInterval: 30,
    autoPolyline: true,
    autoAnchor: true,
    autoAlignGrid: false,
    animateColor: '#30EEDC',
    ruleLineColor: '#FF4101',
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowBlur: 64,
    shadowColor: "#00000014",
    globalAlpha: 1,
    defaultAnchors: [
        {
            x: 0.5,
            y: 0,
        },
        {
            x: 1,
            y: 0.5,
        },
        {
            x: 0.5,
            y: 1,
        },
        {
            x: 0,
            y: 0.5,
        },
    ],
    measureTextWidth: true,
    moveConnectedLine: true,
    mouseRightActive: true,
    disableClipboard: false,
    drawingLineLength: 0,
    disableTouchPadScale: false,
    cdn: '',
    polylineSpace: 10,
    domShapes: [],
    containerShapes: ['tablePlus'],
    textFlip: true,
    textRotate: true,
    unavailableKeys: [],
    diagramOptions: {},
    svgPathStroke: true
}


/**
 * 2D编辑器全局图元外观属性
 */
export const globalEditor2DPen: Editor2DPen = {
    id: '',
    tags: [],
    parentId: '',
    type: undefined,
    name: '',
    lineName: '',
    borderRadius: undefined,
    visible: false,
    locked: undefined,
    close: false,
    length: undefined,
    title: '',
    titleFnJs: '',
    lineWidth: undefined,
    borderWidth: undefined,
    borderColor: '',
    globalAlpha: undefined,
    lineDash: [],
    lineDashOffset: undefined,
    color: '',
    background: '',
    anchorColor: '',
    hoverAnchorColor: '',
    hoverColor: '',
    hoverBackground: '',
    activeColor: '',
    activeBackground: '',
    mouseDownValid: false,
    mouseDownColor: '',
    mouseDownBackground: '',
    bkType: undefined,
    gradientRadius: undefined,
    strokeType: undefined,
    gradientColors: '',
    lineGradientColors: '',
    lineCap: undefined,
    fromLineCap: undefined,
    toLineCap: undefined,
    lineJoin: undefined,
    shadowColor: '',
    shadowBlur: undefined,
    shadowOffsetX: undefined,
    shadowOffsetY: undefined,
    textHasShadow: false,
    text: '',
    textWidth: undefined,
    textHeight: undefined,
    textLeft: undefined,
    textTop: undefined,
    textColor: '',
    hoverTextColor: '',
    activeTextColor: '',
    fontFamily: '',
    fontSize: undefined,
    lineHeight: undefined,
    fontStyle: '',
    fontWeight: '',
    textAlign: undefined,
    textBaseline: undefined,
    textBackground: '',
    whiteSpace: undefined,
    ellipsis: false,
    image: '',
    icon: '',
    iconRotate: undefined,
    iconWidth: undefined,
    iconHeight: undefined,
    iconTop: undefined,
    iconLeft: undefined,
    iconColor: '',
    iconFamily: '',
    iconWeight: '',
    iconSize: undefined,
    iconAlign: undefined,
    imageRatio: false,
    disableInput: false,
    disableRotate: false,
    disableSize: false,
    disableAnchor: false,
    paddingTop: undefined,
    paddingBottom: undefined,
    paddingLeft: undefined,
    paddingRight: undefined,
    backgroundImage: '',
    strokeImage: '',
    children: [],
    followers: [],
    anchors: [],
    anchorRadius: undefined,
    anchorBackground: '',
    pathId: '',
    path: '',
    fromArrow: '',
    toArrow: '',
    fromArrowSize: undefined,
    toArrowSize: undefined,
    fromArrowColor: '',
    toArrowColor: '',
    autoFrom: false,
    autoTo: false,
    connectedLines: [],
    animateCycle: 0,
    nextAnimate: '',
    autoPlay: false,
    playLoop: false,
    duration: undefined,
    linear: true,
    scale: undefined,
    animateSpan: undefined,
    animateColor: '',
    animateLineDash: [],
    animateReverse: false,
    keepAnimateState: false,
    lineAnimateType: undefined,
    frames: [],
    animateList: [],
    animateInterval: undefined,
    animateShadow: false,
    animateShadowColor: '',
    animateShadowBlur: undefined,
    input: false,
    dropdownList: [],
    events: [],
    iframe: '',
    video: '',
    audio: '',
    progress: undefined,
    progressColor: '',
    verticalProgress: false,
    reverseProgress: false,
    progressGradientColors: '',
    externElement: false,
    autoPolyline: false,
    flipX: false,
    flipY: false,
    fillTexts: [],
    hiddenText: false,
    keepDecimal: undefined,
    showChild: undefined,
    animateDotSize: undefined,
    isRuleLine: false,
    canvasLayer: undefined,
    form: [],
    lockedOnCombine: undefined,
    ratio: false,
    animateLineWidth: undefined,
    lineSmooth: undefined,
    gradientSmooth: undefined,
    scrolling: '',
    animations: [],
    currentAnimation: undefined,
    realTimes: [],
    triggers: [],
    crossOrigin: '',
    imageRadius: undefined,
    textFlip: false,
    textRotate: false,
    textAutoAdjust: false,
    dbInput: false,
    operationalRect: undefined,
    blur: undefined,
    blurBackground: '',
    thumbImg: '',
    apiUrl: '',
    apiMethod: '',
    apiHeaders: undefined,
    apiBody: undefined,
    apiEnable: false,
    container: false,
    disabled: false,
    disabledColor: '',
    disabledBackground: '',
    disabledTextColor: '',
    inputType: '',
    deviceId: '',
    pivot: undefined,
    noOnBinds: false,
    interaction: false,
    calculative: {},
    lastConnected: undefined,
    textDecoration: '',
    textDecorationDash: [],
    textDecorationColor: '',
    textStrickoutColor: '',
    textStrickoutDash: [],
    textStrickout: false,
    prevFrame: undefined,
    // 自定义
    dash: '',
    animateType: '',
    description: '',
}

/**
 * 2D编辑器全局配置
 */
export const globalEditor2DConfig: Editor2DConfig = {
    displayMenuTitle: true,
    displayMenuIcon: true,
    disabledTips: '（已禁用）',
}
